DROP DATABASE IF EXISTS bugr;
CREATE DATABASE bugr;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    user_password VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    location VARCHAR(100) NOT NULL,
   	state ENUM('VIC', 'NSW', 'QLD', 'SA', 'WA', 'NT', 'TAS', 'ACT') NOT NULL,
	user_type ENUM('SEEKING', 'OFFERING', 'CARER') NOT NULL,
    about_bug VARCHAR(10000) NOT NULL,
    is_confirmed BIT NOT NULL DEFAULT 0,
    date_registered DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)